name: PolosSearch Deploy

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo Building the App

    # deploy dev
    deploy-development:
        runs-on: ubuntu-latest
        environment:
            name: dev
            url: https://10.0.3.97
        needs: build
        steps:
            - name: Repo Checkout
              uses: actions/checkout@v1
            - name: PolosSearch Deployment
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rlgoDzvc --delete"
                SOURCE: "frontend/"
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ${{vars.TARGET}}